// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v5.26.1
// source: tenant.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// TenantsClient is the client API for Tenants service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TenantsClient interface {
	FindAll(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*TenantList, error)
	FindByNamespace(ctx context.Context, in *TenantNamespaceRequest, opts ...grpc.CallOption) (*Tenant, error)
	Upsert(ctx context.Context, in *Tenant, opts ...grpc.CallOption) (*Tenant, error)
	Delete(ctx context.Context, in *TenantIdRequest, opts ...grpc.CallOption) (*TenantServiceResponse, error)
}

type tenantsClient struct {
	cc grpc.ClientConnInterface
}

func NewTenantsClient(cc grpc.ClientConnInterface) TenantsClient {
	return &tenantsClient{cc}
}

func (c *tenantsClient) FindAll(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*TenantList, error) {
	out := new(TenantList)
	err := c.cc.Invoke(ctx, "/Tenants/FindAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tenantsClient) FindByNamespace(ctx context.Context, in *TenantNamespaceRequest, opts ...grpc.CallOption) (*Tenant, error) {
	out := new(Tenant)
	err := c.cc.Invoke(ctx, "/Tenants/FindByNamespace", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tenantsClient) Upsert(ctx context.Context, in *Tenant, opts ...grpc.CallOption) (*Tenant, error) {
	out := new(Tenant)
	err := c.cc.Invoke(ctx, "/Tenants/Upsert", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tenantsClient) Delete(ctx context.Context, in *TenantIdRequest, opts ...grpc.CallOption) (*TenantServiceResponse, error) {
	out := new(TenantServiceResponse)
	err := c.cc.Invoke(ctx, "/Tenants/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TenantsServer is the server API for Tenants service.
// All implementations must embed UnimplementedTenantsServer
// for forward compatibility
type TenantsServer interface {
	FindAll(context.Context, *emptypb.Empty) (*TenantList, error)
	FindByNamespace(context.Context, *TenantNamespaceRequest) (*Tenant, error)
	Upsert(context.Context, *Tenant) (*Tenant, error)
	Delete(context.Context, *TenantIdRequest) (*TenantServiceResponse, error)
	mustEmbedUnimplementedTenantsServer()
}

// UnimplementedTenantsServer must be embedded to have forward compatible implementations.
type UnimplementedTenantsServer struct {
}

func (UnimplementedTenantsServer) FindAll(context.Context, *emptypb.Empty) (*TenantList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindAll not implemented")
}
func (UnimplementedTenantsServer) FindByNamespace(context.Context, *TenantNamespaceRequest) (*Tenant, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindByNamespace not implemented")
}
func (UnimplementedTenantsServer) Upsert(context.Context, *Tenant) (*Tenant, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Upsert not implemented")
}
func (UnimplementedTenantsServer) Delete(context.Context, *TenantIdRequest) (*TenantServiceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedTenantsServer) mustEmbedUnimplementedTenantsServer() {}

// UnsafeTenantsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TenantsServer will
// result in compilation errors.
type UnsafeTenantsServer interface {
	mustEmbedUnimplementedTenantsServer()
}

func RegisterTenantsServer(s grpc.ServiceRegistrar, srv TenantsServer) {
	s.RegisterService(&Tenants_ServiceDesc, srv)
}

func _Tenants_FindAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TenantsServer).FindAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Tenants/FindAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TenantsServer).FindAll(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tenants_FindByNamespace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TenantNamespaceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TenantsServer).FindByNamespace(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Tenants/FindByNamespace",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TenantsServer).FindByNamespace(ctx, req.(*TenantNamespaceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tenants_Upsert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Tenant)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TenantsServer).Upsert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Tenants/Upsert",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TenantsServer).Upsert(ctx, req.(*Tenant))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tenants_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TenantIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TenantsServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Tenants/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TenantsServer).Delete(ctx, req.(*TenantIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Tenants_ServiceDesc is the grpc.ServiceDesc for Tenants service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Tenants_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Tenants",
	HandlerType: (*TenantsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FindAll",
			Handler:    _Tenants_FindAll_Handler,
		},
		{
			MethodName: "FindByNamespace",
			Handler:    _Tenants_FindByNamespace_Handler,
		},
		{
			MethodName: "Upsert",
			Handler:    _Tenants_Upsert_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _Tenants_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "tenant.proto",
}
